# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package Build
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: npm run build
      - run: npm run pack
      - name: push
        if: ${{ !contains(github.event.head_commit.message, 'update build from CI') }}
        run: |
          git add releases
          if [ $(git status --porcelain | wc -l) -gt "0" ]; then
            git commit -m "update build from CI"
            git push
          fi
