# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package Build
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - "**/*.tgz"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          token: "${{ secrets.ACCESS_TOKEN }}"
      - uses: actions/checkout@v4
        with:
          repository: dimaslanjaka/test-repo
          path: tmp/test-repo
          token: "${{ secrets.ACCESS_TOKEN }}"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        id: cache
        name: init cache
        with:
          path: |
            ./.yarn
            ./yarn.lock
            ./node_modules
            ./tmp
          key: ${{ runner.os }}-${{ hashFiles('**/package.json', '.github') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/package.json', '.github') }}
            ${{ runner.os }}-
      - run: yarn install
      - run: npm run build
      - run: npm run pack
      - run: npm run test:coverage
      - name: push
        if: ${{ !contains(github.event.head_commit.message, 'update build from CI') }}
        run: |
          git config --global user.name "dimaslanjaka"
          git config --global user.email "dimaslanjaka@gmail.com"
          git add releases
          if [ $(git status --porcelain | wc -l) -gt "0" ]; then
            git commit -m "update build from CI"
            git push
          fi
