name: Node.js Package Test

concurrency:
  group: test-${{ github.event.workflow_run.head_sha || github.sha }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows:
      - Build Release
    types:
      - completed

  workflow_dispatch:

  push:

env:
  CI_NODE_VERSION: '24.x'
  CI_PYTHON_VERSION: '3.11'

jobs:
  build:
    name: 🔨 Build & Pack
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: '⬇️ Checkout workflow repository'
        uses: actions/checkout@v6
      - name: '⬇️ Setup CI Environment'
        uses: ./.github/actions/setup-environments
        with:
          node-version: ${{ env.CI_NODE_VERSION }}
          python-version: ${{ env.CI_PYTHON_VERSION }}
          token: ${{ secrets.ACCESS_TOKEN || github.token }}
          prefix-cache-key: '${{ runner.os }}-test-'

      - name: 📦 Install dependencies
        run: |
          touch yarn.lock
          corepack yarn install

      - name: 🔨 Build project
        run: corepack yarn build

      - name: 📦 Pack project
        run: corepack yarn pack

      - name: 📤 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          retention-days: 1
          compression-level: 0
          path: |
            dist/**
            releases/**
            *.tgz
            packages/**/dist/**
            packages/**/*.tgz

  test:
    name: 🧪 Tests
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout workflow repository
        uses: actions/checkout@v6
      - name: ⬇️ Setup CI & Checkout dependencies
        uses: ./.github/actions/setup-environments
        with:
          node-version: ${{ env.CI_NODE_VERSION }}
          token: ${{ secrets.ACCESS_TOKEN || github.token }}

      - name: 📥 Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      # - name: 🧪 Run CJS tests
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || github.token }}
      #   run: |
      #     bash bin/test-cjs \
      #       --coverage=true \
      #       --detectOpenHandles \
      #       --testPathPatterns="${{ github.workspace }}/test/"

      # - name: 🧪 Run ESM tests
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || github.token }}
      #   run: |
      #     bash bin/test-esm \
      #       --coverage=true \
      #       --detectOpenHandles \
      #       --testPathPatterns="${{ github.workspace }}/test/"

      - name: 🧪 Run tests individually
        shell: bash
        run: |
          set -euo pipefail

          find test tests \
            -type f \
            \( -name "*.test.*" -o -name "*.spec.*" \) \
            -print0 |
          while IFS= read -r -d '' file; do
            echo "::group::$file"
            npm test -- "$file"
            echo "::endgroup::"
          done
  cleanup:
    name: 🧹 Clean GitHub Actions Cache
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    # if: always()

    steps:
      - name: 🧹 Clean GitHub Actions Cache
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN || github.token }}
        shell: bash
        run: |
          SHA="${{ github.sha }}"

          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            SHA="${{ github.event.workflow_run.head_sha }}"
          fi

          npx --legacy-peer-deps -y \
            binary-collections@https://raw.githubusercontent.com/dimaslanjaka/bin/master/releases/bin.tgz \
            clean-github-actions-caches \
            --repo "${{ github.repository }}" \
            --sha "$SHA"
