# This workflow runs tests only

name: Node.js Package Test

concurrency:
  group: test-${{ github.event.workflow_run.head_sha }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows:
      - Build Release
    types:
      - completed
  workflow_dispatch:
  push:
    paths:
      - '**/test*/**'
jobs:
  test:
    name: 🧪 Run Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout main repository
        uses: actions/checkout@v6
        with:
          ref: master
          token: '${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}'

      - name: ⬇️ Checkout test-repo
        uses: actions/checkout@v6
        with:
          repository: dimaslanjaka/test-repo
          path: tmp/test-repo
          token: '${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}'
          ref: test

      - name: ⬇️ Checkout packages/git-command-helper
        uses: actions/checkout@v6
        with:
          repository: dimaslanjaka/git-command-helper
          path: packages/git-command-helper
          token: '${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}'
          ref: pre-release

      - name: ⬇️ Checkout packages/cross-spawn
        uses: actions/checkout@v6
        with:
          repository: dimaslanjaka/node-cross-spawn
          path: packages/cross-spawn
          token: '${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}'
          ref: private

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: 🐍 Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: 🐍 Create virtual environment
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate

          python -m pip install --upgrade pip setuptools wheel

          # Install requirements if available
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi

      - uses: actions/cache@v5
        id: cache
        name: 📚 Init cache
        with:
          path: |
            **/.yarn
            **/yarn.lock
            **/node_modules
            **/.venv
            **/venv
            **/__pycache__
            **/*.pyc
            **/tmp/**
            **/*.bak
            .cache/
          key: ${{ runner.os }}-test-${{ hashFiles('**/package.json', '**/requirements*.txt', '.github') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ hashFiles('**/package.json', '**/requirements*.txt', '.github') }}
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: Add custom bins to PATH
        shell: bash
        run: |
          BIN_DIRS=(
            "${{ github.workspace }}/node_modules/.bin"
            "${{ github.workspace }}/vendor/bin"
            "${{ github.workspace }}/.venv/bin"
            "${{ github.workspace }}/venv/bin"
            "${{ github.workspace }}/bin"
            "${{ github.workspace }}/binaries"
          )

          for dir in "${BIN_DIRS[@]}"; do
            if [ -d "$dir" ]; then
              echo "$dir" >> "$GITHUB_PATH"

              # Fix permissions
              chmod -R +x "$dir"

              echo "Added: $dir"
            else
              echo "Skipped missing dir: $dir"
            fi
          done

      - name: 📦 Install dependencies
        run: yarn install

      - name: '📦 Pack project'
        shell: bash
        run: yarn run pack

      - name: 🧪 Run CJS tests with coverage
        run: bash bin/test-cjs --coverage=true --detectOpenHandles --testPathPatterns="${{ github.workspace }}/test/"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: 🧪 Run ESM tests with coverage
        run: bash bin/test-esm --coverage=true --detectOpenHandles --testPathPatterns="${{ github.workspace }}/test/"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: '🧹 Clean GitHub Actions cache (npx)'
        run: npx clean-github-actions-cache
        continue-on-error: true
